TTException: adding a method to fetch the reason an exception is thrown.  Though we don't use this anywhere (at least not yet) it silences compiler warnings about the reason being unused.