in order to build with MSVC TTAttribute needs to be declared after TTObject, otherwise you'll get compiler error C2440
git-svn-id: http://ttblue.googlecode.com/svn/branches/active@376 bc2ad3ca-9a4d-0410-8d14-35da9c29b421